### ISSUE TITLE
How to set n_genes in SCTransform

### ISSUE THREAD

**Issue by SihanLiUVa** [satijalab/sctransform#173] opened 2023-11-06 23:23 UTC
Hi! According to the issue#124, I am trying to increase the number of genes in the function SCTransform. Here are my codes:
group1 <- SCTransform(group1_data,vars.to.regress = "nCount_RNA", ncells = 5000, vst.flavor = "v2", return.only.var.genes = FALSE, n_genes = 5000)
I noticed that in the argument of this function, the n_genes is supposed to pass to sctransform::vst, where the n_genes is used. However, i still got this message from my console. 
Get Negative Binomial regression parameters per gene
Using 2000 genes
Would you please teach me how to pass this argument? Thank you so much in advance!

**Comment by saketkc** [comment] 2023-11-10 17:10
Duplicate of https://github.com/satijalab/seurat/issues/7998

**Closed by saketkc** 2023-11-10 17:10 UTC
